FROM ubuntu:20.04
	
RUN apt-get update
	
COPY iectl /usr/bin

RUN apt-get install -y curl gnupg2 pass
RUN curl -sSL https://get.docker.com/ | sh
RUN apt-get install -y docker-compose

RUN mkdir -p /app/src/workspace
WORKDIR /app/src/workspace
RUN iectl version
RUN iectl publisher workspace init



